AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/GuardClause:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/EmptyElse:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/*.rb'
